Repository Hochfrequenz/kohlrahbi, pull requests merged in 2024-10, with the labels that each got.

#472 ci(conventional commits): Add Labels at PRs
  .github/workflows/conventional-commit-check.yml
Labels: CI/CD

#474 fix(parsing): mixed columns
  src/kohlrahbi/docxtablecells/bodycell.py
  unittests/__snapshots__/test_current_state.ambr
Labels: bug, fix

#455 fix(parsing): handle page breaks within tables
  src/kohlrahbi/ahbtable/ahbsubtable.py
  src/kohlrahbi/ahbtable/ahbtablerow.py
  src/kohlrahbi/docxtablecells/bedinungscell.py
  src/kohlrahbi/docxtablecells/bodycell.py
  unittests/__snapshots__/test_current_state.ambr
  unittests/test_cells/test_bedingung_cell_parser.py
  unittests/test_cells/test_body_cell_parser.py
Labels: fix

#488 fix(file filter): find latest document
  src/kohlrahbi/ahb/command.py
  src/kohlrahbi/docxfilefinder.py
  unittests/test_docxfilefinder.py
Labels: fix
